# Use official Python base image
FROM python:3.10-slim

# Set work directory inside container
WORKDIR /app

# Copy only requirement files first (to leverage Docker cache)
COPY requirements.txt .

# Install dependencies
RUN pip install --no-cache-dir -r requirements.txt

# Copy your project code into the container
COPY . .

# Set environment variables (if needed)
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Run the controller
CMD ["python", "scheduler/controller.py"]