# Generated by Django 5.1.2 on 2025-04-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_periodic',
            field=models.BooleanField(default=False),
        ),
    ]
